apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: attendease-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pixelopscloud/attendease-infra
    targetRevision: main
    path: dev
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: attendease-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
