apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: attendease-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: pixelopscloud/attendease-frontend:b8416b0d04d6e99e2271f7f41d539f2ddcf407b4
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: attendease-dev
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081
